# Generated by Django 5.1.3 on 2024-11-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("post", models.TextField(blank=True, null=True)),
                ("link", models.CharField(max_length=7)),
                ("ig_link", models.URLField()),
                ("x_link", models.URLField()),
                ("linkedIn_link", models.URLField()),
                ("fb_link", models.URLField()),
            ],
        ),
    ]
