# Generated by Django 5.1.3 on 2024-11-18 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="link",
            new_name="like",
        ),
    ]
