# Generated by Django 5.1.3 on 2024-11-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_card_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="number",
            field=models.CharField(default="phone", max_length=11),
        ),
    ]
