# Generated by Django 5.1.3 on 2024-11-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_card_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="number",
        ),
        migrations.AddField(
            model_name="card",
            name="phone_number",
            field=models.CharField(default="phone number", max_length=15),
        ),
        migrations.AddField(
            model_name="card",
            name="whatsapp_number",
            field=models.CharField(default="whatsapp number", max_length=11),
        ),
    ]
